# Generated by Django 3.1.2 on 2020-10-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=50)),
                ('type_of_invoice', models.SmallIntegerField(choices=[(1, 'Withdrawal'), (2, 'Deposit')], default=2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invoice', to='branches.account')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='branches.branch')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_creator', to='baseuser.client')),
            ],
        ),
    ]
